version: '3.5'

services:
  web:
    container_name: feeeed-front
    build: .
    ports:
      - 8080:3000
    privileged: true
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
    command: /bin/sh

networks:
  default:
    name: feeeed-front
